# Generated by Django 5.2.7 on 2025-11-03 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name_plural': 'Préstamos'},
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='autor',
            name='fecha_fallecimiento',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='paginas',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='rating_promedio',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_devolucion_esperada',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categorias',
            field=models.ManyToManyField(to='biblioteca.categoria'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('En reparación', 'En reparación')], default='Disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Devuelto', 'Devuelto'), ('Vencido', 'Vencido')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='resena',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resena',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AddField(
            model_name='libro',
            name='ISBN',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
