# Generated by Django 5.2.8 on 2025-11-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_autor_options_alter_libro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
